name: Feature Request
description: Suggest a new feature or enhancement for PrintHive
title: "[Feature]: "
labels: ["enhancement", "needs triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like PrintHive to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... / Another approach could be...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of PrintHive does this feature relate to?
      options:
        - Printer Management
        - Model Library
        - Print History
        - Timelapse/Video
        - User Management & Authentication
        - Notifications
        - Mobile/UI/UX
        - API/Integration
        - Settings & Configuration
        - Statistics & Analytics
        - File Management
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe how you would use this feature in your workflow
      placeholder: |
        I would use this feature to...
        This would help me when...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots from other apps, or examples
      placeholder: Drag and drop images or paste links here
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, links, or resources about the feature request
      placeholder: Any additional details...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the roadmap/discussions for planned features
          required: true
        - label: This feature aligns with PrintHive's core functionality (3D printer management)
          required: true
